defaults: &defaults 
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: my_user_name
  password: my_passwd
  socket: /var/run/mysqld//mysqld.sock


development:
  database: bzsite_development
  <<: *defaults

test:
  database: bzsite_test
  <<: *defaults

production:
  database: bzsite_production 
  <<: *defaults
